### ISSUE TITLE
Comments on comments.

### ISSUE THREAD

**Issue by PinkFlufflyLlama** [ttauri-project/ttauri_hello_world#1]
https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L83
Should be "its" not "it"

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L39
At a first glance its a little unclear what this relates to, would it be better to also include in brackets after the `"L0T0"` so people know that they are looking at they type declaration.

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L41
is `localizable-text` actually a function too and if so should it have an underscore rather than a hyphen?

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L40
Would it be good to also point out in comments that the first template argument specifies the component type?

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L61
Its very obvious what is happening but if/when there is documentation a comment linking to the page on the other properties available for setting/reading

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L49
"Its" not "It's" - "it's" is the contraction of "it is" where "its" is like "his" or "hers"

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L86
When would this not be the case and what would that look like?

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L117
Would it be better to say "... is called too and in this case it opens the main window"?

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L138
Is the comma needed?

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L156
This is a reference to the main controller window right? May want to add a quick comment saying that.

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L167
What is that instance exactly?

https://github.com/ttauri-project/ttauri_hello_world/blob/main/src/main.cpp#L139
Would it be good to have an example of what a main loop would look like?

**Comment by takev** [comment]
done
