### ISSUE TITLE
Malformed copyright headers

### ISSUE THREAD

**Issue by PinkFlufflyLlama** [ttauri-project/ttauri_hello_world#2]
So, I'm not sure if they are intentionally committed in the first place as it seems like the type of thing that should be generated new at compile time, but the generated locale files in the data/locale/ directory have copyright headers that have not been filled in.

https://github.com/ttauri-project/ttauri_hello_world/tree/main/data/locale

**Comment by takev** [comment]
These files are purely generated, copyright are invalid on these files anyway.
Needs more research if the script needs to pass arguments to fill these in on the .pot file, because the script
probably overwrites that file each time.
